<?php
/**
*<div id="function.fpm-get-status" class="refentry"> <div class="refnamediv">  <h1 class="refname">fpm_get_status</h1>  <p class="verinfo">(PHP 7 &gt;= 7.3, PHP 8)</p><p class="refpurpose"><span class="refname">fpm_get_status</span> &mdash; <span class="dc-title">返回当前 FPM 池状态</span></p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.fpm-get-status-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>fpm_get_status</strong></span>(): <span class="type" style="color:#EAB766"><span class="type" style="color:#EAB766">array</span>|<span class="type" style="color:#EAB766"><span class="type false" style="color:#EAB766">false</span></span></span></div>  <p class="para rdfs-comment">   此函数将返回关联数组，包含当前完整 FPM 池状态。它始终返回完整状态，包含每个进程的状态信息。参阅   <a href="https://www.php.net/manual/zh/fpm.status.php" class="link">FPM 状态页面教程</a>获取有关详细信息。  </p>  <p class="para">   注意如果 FPM 用于服务脚本时才会定义此函数。  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.fpm-get-status-parameters">  <h3 class="title">参数</h3>  <span>此函数没有参数。</span> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.fpm-get-status-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">   包含完整 FPM 池状态的关联数组， 或者在失败时返回 <strong><span>false</span></strong>。  </p> </div></div>
 * @return array|false*/
function fpm_get_status(): array|false {}

/**
*<div id="function.fastcgi-finish-request" class="refentry"> <div class="refnamediv">  <h1 class="refname">fastcgi_finish_request</h1>  <p class="verinfo">(PHP 5 &gt;= 5.3.3, PHP 7, PHP 8)</p><p class="refpurpose"><span class="refname">fastcgi_finish_request</span> &mdash; <span class="dc-title">冲刷(flush)所有响应的数据给客户端</span></p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.fastcgi-finish-request-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>fastcgi_finish_request</strong></span>(): <span class="type" style="color:#EAB766">bool</span></div>  <p class="para rdfs-comment">   此函数冲刷(flush)所有响应的数据给客户端并结束请求。这允许在不打开与客户端之间的连接的情况下执行耗时任务。  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.fastcgi-finish-request-parameters">  <h3 class="title">参数</h3>  <span>此函数没有参数。</span> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.fastcgi-finish-request-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">   成功时返回 <strong><span>true</span></strong>， 或者在失败时返回 <strong><span>false</span></strong>。  </p> </div></div>
 * @return bool Returns TRUE on success or FALSE on failure.*/
function fastcgi_finish_request() {};
