<?php

/**
*<div id="function.phpdbg-break-next" class="refentry"> <div class="refnamediv">  <h1 class="refname">phpdbg_break_next</h1>  <p class="verinfo">(PHP 5 &gt;= 5.6.3, PHP 7, PHP 8)</p><p class="refpurpose"><span class="refname">phpdbg_break_next</span> &mdash; <span class="dc-title">Inserts a breakpoint at the next opcode</span></p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.phpdbg-break-next-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>phpdbg_break_next</strong></span>(): <span class="type" style="color:#EAB766"><span class="type void" style="color:#EAB766">void</span></span></div>  <p class="para rdfs-comment">   Insert a breakpoint at the next opcode.  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.phpdbg-break-next-parameters">  <h3 class="title">参数</h3>  <span>此函数没有参数。</span> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.phpdbg-break-next-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">   没有返回值。  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 seealso" id="refsect1-function.phpdbg-break-next-seealso">  <h3 class="title">参见</h3>  <ul class="simplelist">   <li class="member"><span class="function">{@link phpdbg_break_file()} - Inserts a breakpoint at a line in a file</span></li>   <li class="member"><span class="function">{@link phpdbg_break_function()} - Inserts a breakpoint at entry to a function</span></li>   <li class="member"><span class="function">{@link phpdbg_break_method()} - Inserts a breakpoint at entry to a method</span></li>   <li class="member"><span class="function">{@link phpdbg_clear()} - Clears all breakpoints</span></li>  </ul> </div></div>
*/
function phpdbg_break_next(): void {}

/**
*<div id="function.phpdbg-break-file" class="refentry"> <div class="refnamediv">  <h1 class="refname">phpdbg_break_file</h1>  <p class="verinfo">(PHP 5 &gt;= 5.6.3, PHP 7, PHP 8)</p><p class="refpurpose"><span class="refname">phpdbg_break_file</span> &mdash; <span class="dc-title">Inserts a breakpoint at a line in a file</span></p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.phpdbg-break-file-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>phpdbg_break_file</strong></span>(<span class="methodparam"><span class="type" style="color:#EAB766">string</span> <span class="parameter" style="color:#3A95FF">$file</span></span>, <span class="methodparam"><span class="type" style="color:#EAB766">int</span> <span class="parameter" style="color:#3A95FF">$line</span></span>): <span class="type" style="color:#EAB766"><span class="type void" style="color:#EAB766">void</span></span></div>  <p class="para rdfs-comment">   Insert a breakpoint at the given <span class="parameter" style="color:#3A95FF">line</span> in the given   <span class="parameter" style="color:#3A95FF">file</span>.  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.phpdbg-break-file-parameters">  <h3 class="title">参数</h3>  <dl>       <dt><span class="parameter" style="color:#3A95FF">file</span></dt>    <dd>     <span>      The name of the file.     </span>    </dd>          <dt><span class="parameter" style="color:#3A95FF">line</span></dt>    <dd>     <p class="para">      The line number.     </p>    </dd>     </dl> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.phpdbg-break-file-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">   没有返回值。  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 seealso" id="refsect1-function.phpdbg-break-file-seealso">  <h3 class="title">参见</h3>  <ul class="simplelist">   <li class="member"><span class="function">{@link phpdbg_break_function()} - Inserts a breakpoint at entry to a function</span></li>   <li class="member"><span class="function">{@link phpdbg_break_method()} - Inserts a breakpoint at entry to a method</span></li>   <li class="member"><span class="function">{@link phpdbg_break_next()} - Inserts a breakpoint at the next opcode</span></li>   <li class="member"><span class="function">{@link phpdbg_clear()} - Clears all breakpoints</span></li>  </ul> </div></div>
*/
function phpdbg_break_file(string $file, int $line): void {}

/**
*<div id="function.phpdbg-break-method" class="refentry"> <div class="refnamediv">  <h1 class="refname">phpdbg_break_method</h1>  <p class="verinfo">(PHP 5 &gt;= 5.6.3, PHP 7, PHP 8)</p><p class="refpurpose"><span class="refname">phpdbg_break_method</span> &mdash; <span class="dc-title">Inserts a breakpoint at entry to a method</span></p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.phpdbg-break-method-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>phpdbg_break_method</strong></span>(<span class="methodparam"><span class="type" style="color:#EAB766">string</span> <span class="parameter" style="color:#3A95FF">$class</span></span>, <span class="methodparam"><span class="type" style="color:#EAB766">string</span> <span class="parameter" style="color:#3A95FF">$method</span></span>): <span class="type" style="color:#EAB766"><span class="type void" style="color:#EAB766">void</span></span></div>  <p class="para rdfs-comment">   Insert a breakpoint at the entry to the given <span class="parameter" style="color:#3A95FF">method</span>   of the given <span class="parameter" style="color:#3A95FF">class</span>.  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.phpdbg-break-method-parameters">  <h3 class="title">参数</h3>  <dl>       <dt><span class="parameter" style="color:#3A95FF">class</span></dt>    <dd>     <span>      The name of the class.     </span>    </dd>          <dt><span class="parameter" style="color:#3A95FF">method</span></dt>    <dd>     <p class="para">      The name of the method.     </p>    </dd>     </dl> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.phpdbg-break-method-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">   没有返回值。  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 seealso" id="refsect1-function.phpdbg-break-method-seealso">  <h3 class="title">参见</h3>  <ul class="simplelist">   <li class="member"><span class="function">{@link phpdbg_break_file()} - Inserts a breakpoint at a line in a file</span></li>   <li class="member"><span class="function">{@link phpdbg_break_function()} - Inserts a breakpoint at entry to a function</span></li>   <li class="member"><span class="function">{@link phpdbg_break_next()} - Inserts a breakpoint at the next opcode</span></li>   <li class="member"><span class="function">{@link phpdbg_clear()} - Clears all breakpoints</span></li>  </ul> </div></div>
*/
function phpdbg_break_method(string $class, string $method): void {}

/**
*<div id="function.phpdbg-break-function" class="refentry"> <div class="refnamediv">  <h1 class="refname">phpdbg_break_function</h1>  <p class="verinfo">(PHP 5 &gt;= 5.6.3, PHP 7, PHP 8)</p><p class="refpurpose"><span class="refname">phpdbg_break_function</span> &mdash; <span class="dc-title">Inserts a breakpoint at entry to a function</span></p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.phpdbg-break-function-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>phpdbg_break_function</strong></span>(<span class="methodparam"><span class="type" style="color:#EAB766">string</span> <span class="parameter" style="color:#3A95FF">$function</span></span>): <span class="type" style="color:#EAB766"><span class="type void" style="color:#EAB766">void</span></span></div>  <p class="para rdfs-comment">   Insert a breakpoint at the entry to the given <span class="parameter" style="color:#3A95FF">function</span>.  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.phpdbg-break-function-parameters">  <h3 class="title">参数</h3>  <dl>       <dt><span class="parameter" style="color:#3A95FF">function</span></dt>    <dd>     <span>      The name of the function.     </span>    </dd>     </dl> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.phpdbg-break-function-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">   没有返回值。  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 seealso" id="refsect1-function.phpdbg-break-function-seealso">  <h3 class="title">参见</h3>  <ul class="simplelist">   <li class="member"><span class="function">{@link phpdbg_break_file()} - Inserts a breakpoint at a line in a file</span></li>   <li class="member"><span class="function">{@link phpdbg_break_method()} - Inserts a breakpoint at entry to a method</span></li>   <li class="member"><span class="function">{@link phpdbg_break_next()} - Inserts a breakpoint at the next opcode</span></li>   <li class="member"><span class="function">{@link phpdbg_clear()} - Clears all breakpoints</span></li>  </ul> </div></div>
*/
function phpdbg_break_function(string $function): void {}

/**
*<div id="function.phpdbg-color" class="refentry"> <div class="refnamediv">  <h1 class="refname">phpdbg_color</h1>  <p class="verinfo">(PHP 5 &gt;= 5.6.0, PHP 7, PHP 8)</p><p class="refpurpose"><span class="refname">phpdbg_color</span> &mdash; <span class="dc-title">Sets the color of certain elements</span></p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.phpdbg-color-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>phpdbg_color</strong></span>(<span class="methodparam"><span class="type" style="color:#EAB766">int</span> <span class="parameter" style="color:#3A95FF">$element</span></span>, <span class="methodparam"><span class="type" style="color:#EAB766">string</span> <span class="parameter" style="color:#3A95FF">$color</span></span>): <span class="type" style="color:#EAB766"><span class="type void" style="color:#EAB766">void</span></span></div>  <p class="para rdfs-comment">   Set the <span class="parameter" style="color:#3A95FF">color</span> of the given <span class="parameter" style="color:#3A95FF">element</span>.  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.phpdbg-color-parameters">  <h3 class="title">参数</h3>  <dl>       <dt><span class="parameter" style="color:#3A95FF">element</span></dt>    <dd>     <span>      One of the <strong><span>PHPDBG_COLOR_*</span></strong> constants.     </span>    </dd>          <dt><span class="parameter" style="color:#3A95FF">color</span></dt>    <dd>     <p class="para">      The name of the color. One of <span>white</span>, <span>red</span>,      <span>green</span>, <span>yellow</span>, <span>blue</span>,      <span>purple</span>, <span>cyan</span> or <span>black</span>,      optionally with either a trailing <span>-bold</span> or <span>-underline</span>,      for instance, <span>white-bold</span> or <span>green-underline</span>.     </p>    </dd>     </dl> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.phpdbg-color-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">   没有返回值。  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 seealso" id="refsect1-function.phpdbg-color-seealso">  <h3 class="title">参见</h3>  <ul class="simplelist">   <li class="member"><span class="function">{@link phpdbg_prompt()} - Sets the command prompt</span></li>  </ul> </div></div>
*/
function phpdbg_color(int $element, string $color): void {}

/**
*<div id="function.phpdbg-prompt" class="refentry"> <div class="refnamediv">  <h1 class="refname">phpdbg_prompt</h1>  <p class="verinfo">(PHP 5 &gt;= 5.6.0, PHP 7, PHP 8)</p><p class="refpurpose"><span class="refname">phpdbg_prompt</span> &mdash; <span class="dc-title">Sets the command prompt</span></p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.phpdbg-prompt-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>phpdbg_prompt</strong></span>(<span class="methodparam"><span class="type" style="color:#EAB766">string</span> <span class="parameter" style="color:#3A95FF">$string</span></span>): <span class="type" style="color:#EAB766"><span class="type void" style="color:#EAB766">void</span></span></div>  <p class="para rdfs-comment">   Set the command prompt to the given <span class="parameter" style="color:#3A95FF">string</span>.  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.phpdbg-prompt-parameters">  <h3 class="title">参数</h3>  <dl>       <dt><span class="parameter" style="color:#3A95FF">string</span></dt>    <dd>     <span>      The string to use as command prompt.     </span>    </dd>     </dl> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.phpdbg-prompt-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">   没有返回值。  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 seealso" id="refsect1-function.phpdbg-prompt-seealso">  <h3 class="title">参见</h3>  <ul class="simplelist">   <li class="member"><span class="function">{@link phpdbg_color()} - Sets the color of certain elements</span></li>  </ul> </div></div>
*/
function phpdbg_prompt(string $string): void {}

/**
*<div id="function.phpdbg-exec" class="refentry"> <div class="refnamediv">  <h1 class="refname">phpdbg_exec</h1>  <p class="verinfo">(PHP 5 &gt;= 5.6.0, PHP 7, PHP 8)</p><p class="refpurpose"><span class="refname">phpdbg_exec</span> &mdash; <span class="dc-title">Attempts to set the execution context</span></p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.phpdbg-exec-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>phpdbg_exec</strong></span>(<span class="methodparam"><span class="type" style="color:#EAB766">string</span> <span class="parameter" style="color:#3A95FF">$context</span></span>): <span class="type" style="color:#EAB766"><span class="type" style="color:#EAB766">string</span>|<span class="type" style="color:#EAB766">bool</span></span></div>  <p class="para rdfs-comment">  </p>  <div class="warning"><strong class="warning">警告</strong><p class="simpara">本函数还未编写文档，仅有参数列表。</p></div> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.phpdbg-exec-parameters">  <h3 class="title">参数</h3>  <dl>       <dt><span class="parameter" style="color:#3A95FF">context</span></dt>    <dd>     <span>           </span>    </dd>     </dl> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.phpdbg-exec-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">   If the execution context was set previously it is returned.   If the execution context was not set previously <strong><span>true</span></strong> is returned.   If the request to set the context fails, <strong><span>false</span></strong> is returned, and an   <strong><span>E_WARNING</span></strong> raised.  </p> </div></div>
 * @return string|bool*/
function phpdbg_exec(string $context) {}

/**
*<div id="function.phpdbg-clear" class="refentry"> <div class="refnamediv">  <h1 class="refname">phpdbg_clear</h1>  <p class="verinfo">(PHP 5 &gt;= 5.6.0, PHP 7, PHP 8)</p><p class="refpurpose"><span class="refname">phpdbg_clear</span> &mdash; <span class="dc-title">Clears all breakpoints</span></p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.phpdbg-clear-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>phpdbg_clear</strong></span>(): <span class="type" style="color:#EAB766"><span class="type void" style="color:#EAB766">void</span></span></div>  <p class="para rdfs-comment">   Clear all breakpoints that have been set, either via one of the   <span class="function"><strong style="color:#CC7832">phpdbg_break_*()</strong></span> functions or interactively in the console.  </p>  <div class="warning"><strong class="warning">警告</strong><p class="simpara">本函数还未编写文档，仅有参数列表。</p></div> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.phpdbg-clear-parameters">  <h3 class="title">参数</h3>  <span>此函数没有参数。</span> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.phpdbg-clear-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">   没有返回值。  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 seealso" id="refsect1-function.phpdbg-clear-seealso">  <h3 class="title">参见</h3>  <ul class="simplelist">   <li class="member"><span class="function">{@link phpdbg_break_file()} - Inserts a breakpoint at a line in a file</span></li>   <li class="member"><span class="function">{@link phpdbg_break_function()} - Inserts a breakpoint at entry to a function</span></li>   <li class="member"><span class="function">{@link phpdbg_break_method()} - Inserts a breakpoint at entry to a method</span></li>   <li class="member"><span class="function">{@link phpdbg_break_next()} - Inserts a breakpoint at the next opcode</span></li>  </ul> </div></div>
*/
function phpdbg_clear(): void {}

/**
*<div id="function.phpdbg-start-oplog" class="refentry"> <div class="refnamediv">  <h1 class="refname">phpdbg_start_oplog</h1>  <p class="verinfo">(PHP 7, PHP 8)</p><p class="refpurpose"><span class="refname">phpdbg_start_oplog</span> &mdash; <span class="dc-title"> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.phpdbg-start-oplog-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>phpdbg_start_oplog</strong></span>(): <span class="type" style="color:#EAB766"><span class="type void" style="color:#EAB766">void</span></span></div>  <p class="para rdfs-comment">  </p>  <div class="warning"><strong class="warning">警告</strong><p class="simpara">本函数还未编写文档，仅有参数列表。</p></div> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.phpdbg-start-oplog-parameters">  <h3 class="title">参数</h3>  <span>此函数没有参数。</span> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.phpdbg-start-oplog-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">   没有返回值。  </p> </div></div>
*/
function phpdbg_start_oplog(): void {}

/**
*<div id="function.phpdbg-end-oplog" class="refentry"> <div class="refnamediv">  <h1 class="refname">phpdbg_end_oplog</h1>  <p class="verinfo">(PHP 7, PHP 8)</p><p class="refpurpose"><span class="refname">phpdbg_end_oplog</span> &mdash; <span class="dc-title"> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.phpdbg-end-oplog-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>phpdbg_end_oplog</strong></span>(<span class="methodparam"><span class="type" style="color:#EAB766">array</span> <span class="parameter" style="color:#3A95FF">$options</span><span class="initializer"> = []</span></span>): <span class="type" style="color:#EAB766"><span class="type" style="color:#EAB766">?</span><span class="type" style="color:#EAB766">array</span></span></div>  <p class="para rdfs-comment">  </p>  <div class="warning"><strong class="warning">警告</strong><p class="simpara">本函数还未编写文档，仅有参数列表。</p></div> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.phpdbg-end-oplog-parameters">  <h3 class="title">参数</h3>  <dl>       <dt><span class="parameter" style="color:#3A95FF">options</span></dt>    <dd>     <span>           </span>    </dd>     </dl> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.phpdbg-end-oplog-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">     </p> </div></div>
*/
function phpdbg_end_oplog(array $options = []): ?array {}

/**
*<div id="function.phpdbg-get-executable" class="refentry"> <div class="refnamediv">  <h1 class="refname">phpdbg_get_executable</h1>  <p class="verinfo">(PHP 7, PHP 8)</p><p class="refpurpose"><span class="refname">phpdbg_get_executable</span> &mdash; <span class="dc-title"> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.phpdbg-get-executable-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>phpdbg_get_executable</strong></span>(<span class="methodparam"><span class="type" style="color:#EAB766">array</span> <span class="parameter" style="color:#3A95FF">$options</span><span class="initializer"> = []</span></span>): <span class="type" style="color:#EAB766">array</span></div>  <p class="para rdfs-comment">  </p>  <div class="warning"><strong class="warning">警告</strong><p class="simpara">本函数还未编写文档，仅有参数列表。</p></div> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.phpdbg-get-executable-parameters">  <h3 class="title">参数</h3>  <dl>       <dt><span class="parameter" style="color:#3A95FF">options</span></dt>    <dd>     <span>           </span>    </dd>     </dl> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.phpdbg-get-executable-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">     </p> </div></div>
*/
function phpdbg_get_executable(array $options = []): array {}
