<?php

/**
*<div id="function.lzf-compress" class="refentry"> <div class="refnamediv">  <h1 class="refname">lzf_compress</h1>  <p class="verinfo">(PECL lzf &gt;= 0.1.0)</p><p class="refpurpose"><span class="refname">lzf_compress</span> &mdash; <span class="dc-title">   LZF compression  </span></p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.lzf-compress-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>lzf_compress</strong></span>(<span class="methodparam"><span class="type" style="color:#EAB766">string</span> <span class="parameter" style="color:#3A95FF">$data</span></span>): <span class="type" style="color:#EAB766">string</span></div>  <p class="para rdfs-comment">   <span class="function"><strong style="color:#CC7832">lzf_compress()</strong></span> compresses the given   <span class="parameter" style="color:#3A95FF">data</span> string using LZF encoding.  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.lzf-compress-parameters">  <h3 class="title">参数</h3>  <span>   <dl>         <dt><span class="parameter" style="color:#3A95FF">data</span></dt>     <dd>      <p class="para">       The string to compress.      </p>     </dd>       </dl>  </span> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.lzf-compress-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">   Returns the compressed data or <strong><span>false</span></strong> if an error occurred.  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 seealso" id="refsect1-function.lzf-compress-seealso">  <h3 class="title">参见</h3>  <span>   <ul class="simplelist">    <li class="member"><span class="function">{@link lzf_decompress()} - LZF decompression</span></li>   </ul>  </span> </div></div>
 * @return false|string Returns the compressed data or FALSE if an error occurred.*/
function lzf_compress($data) {}

/**
*<div id="function.lzf-decompress" class="refentry"> <div class="refnamediv">  <h1 class="refname">lzf_decompress</h1>  <p class="verinfo">(PECL lzf &gt;= 0.1.0)</p><p class="refpurpose"><span class="refname">lzf_decompress</span> &mdash; <span class="dc-title">   LZF decompression  </span></p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.lzf-decompress-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>lzf_decompress</strong></span>(<span class="methodparam"><span class="type" style="color:#EAB766">string</span> <span class="parameter" style="color:#3A95FF">$data</span></span>): <span class="type" style="color:#EAB766">string</span></div>  <p class="para rdfs-comment">   <span class="function">{@link lzf_compress()}</span> decompresses the given   <span class="parameter" style="color:#3A95FF">data</span> string containing lzf encoded data.  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.lzf-decompress-parameters">  <h3 class="title">参数</h3>  <span>   <dl>         <dt><span class="parameter" style="color:#3A95FF">data</span></dt>     <dd>      <p class="para">       The compressed string.      </p>     </dd>       </dl>  </span> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.lzf-decompress-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">   Returns the decompressed data or <strong><span>false</span></strong> if an error occurred.  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 seealso" id="refsect1-function.lzf-decompress-seealso">  <h3 class="title">参见</h3>  <span>   <ul class="simplelist">    <li class="member"><span class="function">{@link lzf_compress()} - LZF compression</span></li>   </ul>  </span> </div></div>
 * @return false|string Returns the decompressed data or FALSE if an error occurred.*/
function lzf_decompress($data) {}

/**
*<div id="function.lzf-optimized-for" class="refentry"> <div class="refnamediv">  <h1 class="refname">lzf_optimized_for</h1>  <p class="verinfo">(PECL lzf &gt;= 1.0.0)</p><p class="refpurpose"><span class="refname">lzf_optimized_for</span> &mdash; <span class="dc-title">   Determines what LZF extension was optimized for  </span></p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 description" id="refsect1-function.lzf-optimized-for-description">  <h3 class="title">说明</h3>  <div class="methodsynopsis dc-description">   <span class="methodname" style="color:#CC7832"><strong>lzf_optimized_for</strong></span>(): <span class="type" style="color:#EAB766">int</span></div>  <p class="para rdfs-comment">   Determines what was LZF extension optimized for during compilation.  </p> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 parameters" id="refsect1-function.lzf-optimized-for-parameters">  <h3 class="title">参数</h3>  <span>此函数没有参数。</span> </div> <br></br><div style="BORDER-TOP: gray 1px dashed; OVERFLOW: hidden; HEIGHT: 1px"></div><div class="refsect1 returnvalues" id="refsect1-function.lzf-optimized-for-returnvalues">  <h3 class="title">返回值</h3>  <p class="para">   Returns 1 if LZF was optimized for speed, 0 for compression.  </p> </div></div>
 * @return int Returns 1 if LZF was optimized for speed, 0 for compression.*/
function lzf_optimized_for() {}
